version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-ip-tracker
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: mongo-ip-tracker
    ports:
      - "27017:27017"