version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis-ip-tracker
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: mongo-ip-tracker
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: api-ip-tracker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

  worker:
    build: .
    container_name: worker-ip-tracker
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

  beat:
    build: .
    container_name: beat-ip-tracker
    command: celery -A app.workers.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app